### ISSUE TITLE
Add clang-format git integration and clang-format installation script

### ISSUE THREAD

**Issue by sherry-yuan** [intel/fpga-runtime-for-opencl#54]
User may have different clang-format version locally, and therefore running their local clang-format may cause workflow runs to fail. It will be nice if the clang-format can be pushed directly to forked repo's branch to avoid copying clang format changes.

Or an alternative is to document which clang-format version to run.

**Comment by pcolberg** [comment]
The `clang-format` pull-request workflow runs in the context of the origin/target, i.e., this repository, and I would think that the [`GITHUB_TOKEN` does not have write permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) to the fork/source repository either. Even if it were permitted, I would be cautious about pushing commits from a workflow, for security but also for usability concerns. The workflow commits are not automatically reflected in the local repository of the user, which may lead to surprises, e.g., pull conflicts or force-push accidents when further local changes were committed after the initial push.

How about turning the proposal for documentation into a script that helps with the semi-automatic installation of `clang-format`? We could test this very simple script as part of the [clang container](https://github.com/intel/fpga-runtime-for-opencl/blob/c9cca6eed52b7ddf616bfac1ce97271a70ce6806/container/ubuntu-20.04-clang/Dockerfile) build, e.g., a script that takes the installation directory as the only argument and maybe prints copy-pasteable instructions for the common case of extending `PATH` in `~/.bashrc` (which the contributor obviously knows, it would be merely for their convenience).

In addition, we could provide an opt-in [`pre-commit` git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_committing_workflow_hooks) that automatically runs `clang-format` (from `PATH`) before creating a commit, which could be installed by running a setup script that symlinks the hook into `~/.git/hooks`. This would be opt-in since `clang-format` may already be run automatically as part of the contributor's editor.

**Comment by pcolberg** [comment]
Regarding the `pre-commit` hook, this actually seems to go against the intended use, which is to check rather than modify the code to be committed. When the `pre-commit` hook is invoked through `git commit`, the contributor has most likely already **staged** their changes (and potentially partially using `git add -p`), such that modifications could again lead to surprises.

LLVM provides a [clang-format git integration](https://github.com/llvm/llvm-project/blob/9e634b35ff51d0eb2b38013111491e88bdbae388/clang/tools/clang-format/git-clang-format), would this be useful?

**Comment by sherry-yuan** [comment]
> How about turning the proposal for documentation into a script that helps with the semi-automatic installation of `clang-format`?

Yes this is a great idea! And yes, the concern make sense, surprises&potential merge conflict will not make it easier.



> LLVM provides a [clang-format git integration](https://github.com/llvm/llvm-project/blob/9e634b35ff51d0eb2b38013111491e88bdbae388/clang/tools/clang-format/git-clang-format), would this be useful?

Yes it seems to do exactly what we need, thank you!

**Comment by pcolberg** [comment]
> Edit: nevermind, given this might be used in the workflow, we probably want to keep it in script just to be consistent.

Yes, keeping these helper scripts under `scripts` is fine for now. To summarize, the proposal is for the script to be used both manually by the contributor to install a matching `clang-format` on their (Linux x86_64) machine, and automatically by the [`clang` container](https://github.com/intel/fpga-runtime-for-opencl/blob/721e05512df7e20fa802181e0e1be4edf5455690/container/ubuntu-20.04-clang/Dockerfile) build. A new section in [CONTRIBUTING.md](https://github.com/intel/fpga-runtime-for-opencl/blob/721e05512df7e20fa802181e0e1be4edf5455690/CONTRIBUTING.md) can point to this script and also the `git clang-format` script.

**Comment by pcolberg** [comment]
I have thought a bit more and your initial proposal of documenting our use of clang-format, the extact version, and links to the upstream binaries for various OS, might serve a wider number of users. The [clang container](https://github.com/intel/fpga-runtime-for-opencl/blob/fc99b92704a466f7dc4d84bd45d465d64d03dbb0/container/ubuntu-20.04-clang/Dockerfile) uses the binaries for Ubuntu 20.04, whereas users might need binaries for older distributions; at that point simply providing the link to the corresponding LLVM release page seems as effective and a script provides little benefit. What do you think?

**Comment by sherry-yuan** [comment]
> The [clang container](https://github.com/intel/fpga-runtime-for-opencl/blob/fc99b92704a466f7dc4d84bd45d465d64d03dbb0/container/ubuntu-20.04-clang/Dockerfile) uses the binaries for Ubuntu 20.04, whereas users might need binaries for older distributions; at that point simply providing the link to the corresponding LLVM release page seems as effective and a script provides little benefit. What do you think?

I think that is a good idea, there are so many variants of OS, it is probably nice for user to decide which ones they want to install for themselves. I think the documentation will need to point out that for fedora, centos, suse os, use gnu-ubuntu. (since this is not clear at first glance)
